---
title: "Keeping the Bootcamp Fun Alive!"
author: "Jeff Hollister"
date: "Wednesday, May 21, 2014"
output: pdf_document
---
In the later part of 2013, I started the process of co-hosting a Bootcamp with [Peter August](), [Judith Swift]() both from the University of Rhode Island (URI).  During our discussions it became quite clear that as fantastic as the bootcamps are, it would be even better if we could extend the opportunities for learning.  We tossed around several ideas but eventually decided we would try a special topics course at URI.  Thus, [Scientific Computing and Programming for Coastal Resource Managment](http://scicomp2014.edc.uri.edu/) was born.  We opened the course up to any of the bootcamp participants who had an interest and official enrollment in the course was not required.  In the end we had about 10 regulars attend the classes and a few students who enrolled for credit. Pete August, myself, and Adam Smith coordinated the course.  

The content of the course was mostly coordinated by the students, with some classes led by myself, Adam, or Pete.  Since the content was largely up to the interests of the class, we did need a way to reinforce the lessons taught in the [bootcamp](http://iglpdc.github.io/2014-01-13-uri/).  To do this, we used blog posts, written in R Markdown, and turned in via Pull Requests as the mechanism for adding content to the course and reinforcing some of the version control lessons.  In the end, the [course covered material](http://scicomp2014.edc.uri.edu/posts.html) from spatial data handling in R, to image processing in R, to pivot table like operations in R, to extracting zip codes from messy data.

