---
layout: post
title: Spatial Data Analysis with R
author: Jeff Hollister
---

I could have entitled this post "How to Ditch ArcGIS", but that is probably a bit over the top.  Thus the more pedestrian title.  Which is OK, becuase either title would be accurate.

So, my plans with the post are to introduce you to the concept of using R as a GIS.  This idea would have seemed a bit silly not too long ago and most R gurus would have suggested you simply transfer data between R and your GIS of choice (e.g. [ArcGIS](http://www.esri.com/software/arcgis), [GRASS](http://grass.osgeo.org/), [QGIS](http://www.qgis.org/en/site/), etc.).   But over the last several years there has been a suite of packages released that provide nearly all the analytical functionality of a full bore GIS.  I will provide details on a number of packages that either allow R to connect to a GIS or allow R to serve as a GIS.  The later is how I work these days.  

# Packages for Connecting R with a GIS

This section shows two packages that allow you to connect to an external GIS and run processes.  These work well if you have familiarity with and access to an existing GIS.  

First is`spgrass6`.  This allows for either the running of R from within a GRASS session, or access to GRASS commands from within an R session.  As I don't currently have GRASS running on my machine, I am not going to show examples.  If you have interest, I encourage you to dig through the help (e.g. `??spgrass6`).

The second option is `RPyGeo`, which is a package that provides access to ArcGIS geoprocessing tools via an intermediate Python script.  File I/0 still needs to be handeled (see below), but `RPyGeo` allows consolidation of the workflow to a single language. As an example, here is an example that buffers a shapefile.

```{r rpygeoExamp, eval= FALSE}
# Installs if not already
if(!"RPyGeo"%in%installed.packages()){
  install.packages("RPyGeo")
}
library(RPyGeo)
# Files availbfrom from figshare at
# http://dx.doi.org/10.6084/m9.figshare.796429
rpygeo.geoprocessor("Buffer_analysis",
args=list("sampleLoc.shp","sampleLocB.shp","1000 meters"))

```

Two downsides to this are it requires ArcGIS (and its associated cost) and for every geoprocessing step it creates a python script, fires up Arc, runs the command, and closes down Arc.  This is a bit resource heavy and slows down the analysis considerably.  Not much of an issue with smaller tasks, but for those analyses that are operating on many features idependently and/or have many steps, this can be a hinderance.

# Packages for Using R as a GIS

While the above options provide the full functionality of a GIS (e.g. ArcGIS), they do require additional software, licenses, maintanenace, resources, etc.  Another, more streamlined solution for integrating R and GIS is to use several packages that prove a (mostly) pure R solution. As I said, this is a recently (e.g. last 2-3 years) added functionality to R.

The standard packages that most use to imbed GIS functionality to R are listed below with a bit of annotation on each.

1. `sp`: This is one of the foundational packages for dealing with spatial data in R.  It sets up the spatial data classes (e.g. `SpatialLines`, `SpatialPolygonsDataFrame`, etc.) that are used (or at least recognized) by all of the other packages. Some analysis also included in `sp`. 
2. `rgdal`: This is another of the foundational packages, that is built of the [Geospatial Data Abstraction Library](http://www.gdal.org/).  This provides most of the utilities you will need to read and write a variety of geospatial data formats.
3. `rgeos`: This package provides an R interface to [GEOS (Geometry Engine, Open Source)](http://trac.osgeo.org/geos/).  This gives you most of what you typically think of as "GISy" analysis.
4. `raster`: Allows processing and analysis of raster data and also provides capability to deal with large rasters by being able to read data from disk.

And, some other useful additional packages:

1. `gdistance`: Provides tools for doing a variety of cost surface based analyses
2. `geosphere`: Calculates Great Circle distances and provides a variety of tools for dealing with distances, bearings, etc.
3. `landsat`: Provides processing and correction tools multi-spectral imagery (and shout out to co-maintaner of r-sig-ecology, [Sarah Goslee](http://www.ars.usda.gov/pandp/people/people.htm?personid=31752)).
4. `maptools`: Another widely used package to faciliate reading and writing spatial data.

# Examples

In this section, I provide 

# What's missing?


# Getting Help

Aside from the normal places for getting help with R related issues (e.g. Stackoverflow, etc.).  Three additional and related sources of help are:
1. [CRAN Analysis of Spatial Data Task View](http://cran.r-project.org/web/views/Spatial.html) 
2. [r-sig-geo](https://stat.ethz.ch/mailman/listinfo/R-SIG-Geo/)
3. []()


