---
layout: post
title: Reproducible Presentations: Slidify and RStudio
author: Jeff Hollister
---

The goals for this post is to introduce the concept of using R Markdown to create reproducible presentations (aka, how to ditch Powerpoint).  I am going to show two different ways to do this one with an R package `slidify` and another with R Presentations in R Studio.  As we go through this, you should hopefully see a lot of overlap in what you have already seen with writing blog posts.  In other words, the tools are the same, just some different processing steps to get the final output.

During today's class we will cover the basics of styling, YAML, Markdown, output frameworks, and display.  If there is time, I will give a presentation, created with `slidify`, on blogging and social media for scientists just so you can see one of these in action.

# Few things to think about

As the standard for presentations for so long has been .ppt(x), using a different format requires a bit of a shift in thinking.  Some things to keep in mind:

1. Output format is html5
2. Simply display using a browser
3. Printing and pdf creation possible: Some options better than others

# Styling

Styling tends to be one of the biggest sources of dithering when it comes to creating presentations (for associated developer term see [yak shaving](http://en.wiktionary.org/wiki/yak_shaving)) .  Reproducible presentaitons are no different.  Only difference is you do need to know some CSS in order to customize presenations yourself.

We are not going to spend too much time on this, but if you want to see some of what is required to make changes you can (warning: shameless self-promotion ahead) read through a blog post of mine on the general 

# Required YAML

# Output Frameworks

# Display


